# -*- coding: utf-8 -*-
"""UZD2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ejAkBMYWkq019RQuQ5Q_k64LZ0eXHczB

## Simona Gelžinytė, DM_4k_2gr

## Reguliariosios išraiškos

#### Importuokite Reguliariosioms išraiškoms tvarkyti skirtą Python biblioteką
"""

import re

"""#### 1. Surastkite visus skaitmenis esančius šiame tekste"""

tekstas ="During the 1970s, many programmers began to write conceptual ontologies, which structured real-world information into computer-understandable data. Examples are MARGIE (Schank, 1975), SAM (Cullingford, 1978), PAM (Wilensky, 1978), TaleSpin (Meehan, 1976), QUALM (Lehnert, 1977), Politics (Carbonell, 1979), and Plot Units (Lehnert 1981). During this time, the first many chatterbots were written (e.g., PARRY)."
def getNumbers(tekstas):
    rez = re.findall(r'[0-9]+', tekstas)
    return rez

rez = getNumbers(tekstas)
print(rez)

"""#### 2. Suraskite visus simbolius tik ne skaitmenis esančius nurodytame tekste"""

tekstas="During the 1970s, many programmers began to write conceptual ontologies, which structured real-world information into computer-understandable data. Examples are MARGIE (Schank, 1975), SAM (Cullingford, 1978), PAM (Wilensky, 1978), TaleSpin (Meehan, 1976), QUALM (Lehnert, 1977), Politics (Carbonell, 1979), and Plot Units (Lehnert 1981). During this time, the first many chatterbots were written (e.g., PARRY)."
def getSymbols(tekstas):
    rez = re.findall(r'\D+', tekstas)
    return rez

rez = getSymbols(tekstas)
print(rez)

"""#### 3. Suraskite visus skyrybos ženklus esančius nurodytame tekste"""

tekstas="Sveiki. Šaunu, kad susirinkote!?"
def getPunc(tekstas):
    rez = re.findall(r'[.,!?]', tekstas)
    return rez

rez = getPunc(tekstas)
print(rez)

"""#### 4. Iš teksto pašalinkite skyrybos ženklus."""

tekstas="Sveiki. Šaunu, kad susirinkote!?"
def getNoSymbols(tekstas):
    rez = ''.join(re.findall(r'[^.,?!]', tekstas))
    return rez

rez = getNoSymbols(tekstas)
rez

"""#### 5. Iš teksto pašalinkite tarpus"""

tekstas="Sveiki. Šaunu, kad susirinkote!?"
def getNoSpace(tekstas):
    pattern=r"\s+"
    s = ''.join(re.sub(pattern, "", tekstas))
    return str(s)

rez = getNoSpace(tekstas)
rez

"""#### 6. Pateiktame tekste suraskite  visus žodžius su brūkšneliu"""

tekstas="Paskelbti 1-osios ir 3-osios vietų laimėtojai"
def gett(tekstas):
  rez = re.findall(r'[\w]+-[\w]+' ,tekstas)

  return rez

rez = gett(tekstas)
print(rez)

"""#### 7. Pateikite visus tekste esančius elektroninio pašto adresus"""

tekstas="Sveiki, visas bendras užklausas siųskite adresu info@mano.lt. Jei turite klausimų, susijusių su uždavinių sprendimu, siųskite juos adresu uzdaviniai@mano.lt. Dėl techninių problemų kreipkitės adresu pagalba@mano.lt."
def getEmail(tekstas):
  rez = re.findall('\S+@\S+', tekstas)
  return rez

rez = getEmail(tekstas)
print(rez)

"""#### 8. Iš 7-me uždavinyje gautų el. pašto adresų gaukite visus vartotojų  vardus."""

tekstas="Sveiki, visas bendras užklausas siųskite adresu info@mano.lt. Jei turite klausimų, susijusių su uždavinių sprendimu, siųskite juos adresu uzdaviniai@mano.lt. Dėl techninių problemų kreipkitės adresu pagalba@mano.lt."
def getName(tekstas):
  rez = re.findall('\S+@', tekstas)
  tekstas = str(rez)
  rez1 = ''.join(re.findall(r'[^@]', tekstas))
  return rez1

rez = getName(tekstas)
print(rez)