# -*- coding: utf-8 -*-
"""UZD3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlTv9-KkgDtsdCWVPpbRQpbOGv6bY4Sy
"""

tekstas="Welcome to Vilnius University – the oldest and largest Lithuanian higher education institution. Since its establishment in the 16th century, Vilnius University, as integral part of European science and culture has embodied the concept­ of a classical university and the unity of studies and research. Vilnius University is an active participant in international scientific and academic activities and boasts many prominent scientists, professors and graduates. Scientific development and the expanding relations with global research centres have contributed to the variety of research and studies at Vilnius University. With the support of social partners, the university educates globally–minded specialists who successfully integrate in the modern European community."
print(tekstas)

"""## Teksto skaidymas į teksto vienetus (angl. Tokenization)

#### 1. Kiek žodžių ir skyrybos ženklų yra tekste?
Apskaičiuokite naudodamiesi SpaCy biblioteka
"""

import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(tekstas)
len(doc)

"""#### 2. Kiek žodžių ir skyrybos ženklų  yra tekste?
Apskaičiuokite naudodamiesi NLTK biblioteka
"""

import nltk
nltk.download("punkt")
doc= nltk.word_tokenize(tekstas)
length = len(doc)
length

"""#### 3. Kiek sakinių yra tekste?
Apskaičiuokite naudodamiesi SpaCy biblioteka
"""

doc=nlp(tekstas)
num_sent=len(list(doc.sents))
num_sent

"""#### 4. Kiek sakinių yra tekste?
Apskaičiuokite naudodamiesi NLTK biblioteka
"""

sentences= nltk.sent_tokenize(tekstas)
length= len(sentences)
length

"""#### 5. Atspausdinkite ketvirtą pateikto teksto sakinį"""

doc = nlp(tekstas)
doc_sents = [sent for sent in doc.sents]
print(doc_sents[3])

"""#### 6. Išskaidykite ketvirtą sakinį į žodžius ir skyrybos ženklus."""

doc = nlp(tekstas)
doc = doc_sents[3]
for sent in doc.sents:
   print([ token.text for token in sent])

"""# Pagrindinės žodžio formos nustatymas

#### 7. Ketvirto sakinio žodžiams nustatykite pagrindines formas
"""

from spacy.tokens import token
doc = nlp(tekstas)
doc_sents = [sent for sent in doc.sents]
doc = doc_sents[3]
for token in doc:
  print(token.text, '\t', token.lemma_)

"""## Žodžių kamienų išskyrimas

#### 8. Ketvirto sakinio žodžiams išskirkite kamienus¶
"""

from nltk.tokenize import word_tokenize
nltk.download("punkt")
sentences= nltk.sent_tokenize(tekstas)
words = sentences[3]
sent = nltk.word_tokenize(words)


from nltk.stem.porter import *
p_stemmer = PorterStemmer()
for word in sent:
  print(word+'\t'+p_stemmer.stem(word))

"""#### 9. Iš turimo teksto pašalinkite nereikšmingus žodžius (angl. stop words) is skyrybos ženklus"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
def getNoSymbols(tekstas):
    rez = ''.join(re.findall(r'[^.,?!–]', tekstas))
    return rez

rez = getNoSymbols(tekstas)
tekstas = rez
word_tokens = word_tokenize(tekstas)
filtered_sentence = []

for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)

print(filtered_sentence)

"""# Darbas su lietuvišku tekstu"""

tekstas2="Vilniaus universitetas (VU) – pirmasis ir didžiausias Lietuvos universitetas, įsikūręs šalies sostinėje Vilniuje ir turintis po padalinį Kaune ir Šiauliuose. Įkurtas 1579 m. VU yra šalies lyderis absoliučioje daugumoje mokslo ir studijų krypčių. Būdamas viena seniausių ir žymiausių Vidurio ir Rytų Europos aukštųjų mokyklų, VU darė didelę įtaką ne tik Lietuvos, bet ir kaimyninių šalių kultūriniam gyvenimui, išugdė ne vieną mokslininkų, poetų, kultūros veikėjų kartą. VU profesoriavo ir mokėsi daug garsių asmenybių: medikai vokiečiai Johanas Frankas ir jo sūnus Jozefas Frankas, istorikas Joachimas Lelevelis, poetai Adomas Mickevičius ir Julius Slovackis, istorikas Simonas Daukantas, rašytojas, poetas ir literatūros mokslininkas Česlovas Milošas. VU įkurtas sklindant renesanso, reformacijos ir katalikiškosios reformos idėjoms. Už VU anksčiau Europoje įkurti tik Prahos, Krokuvos, Pečo, Budapešto, Bratislavos ir Karaliaučiaus universitetai."

"""#### 10. Išskaidykite pirmąjį sakinį į žodžius ir skyrybos ženklus."""

import spacy

nlp = spacy.load("en_core_web_sm")
doc2 = nlp(tekstas2)
doc2_sents = [sent for sent in doc2.sents]
doc2 = doc2_sents[0]
for sent in doc2.sents:
   print([ token.text for token in sent])

"""#### 11. Penktojo sakinio žodžiams nustatykite pagrindines formas"""

!spacy download lt_core_news_sm

from spacy.tokens import token

nlp = spacy.load("lt_core_news_sm")
doc2 = nlp(tekstas2)
doc2_sents = [sent for sent in doc2.sents]
doc22 = doc2_sents[5]

for token in doc22:
  print(token.text, '\t', token.lemma_)

"""#### 12. Iš turimo teksto pašalinkite nereikšmingus žodžius (angl. stop words) is skyrybos ženkus"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
def getNoSymbols(tekstas2):
    rez = ''.join(re.findall(r'[^.,?!–)()]', tekstas2))
    return rez

rez = getNoSymbols(tekstas2)
tekstas2 = rez
word_tokens = word_tokenize(tekstas2)
filtered_sentence = []

for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)

print(filtered_sentence)